In [19]:
import numpy as np
import math
import random
import matplotlib
import matplotlib.pyplot as plt
from itertools import count

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# set up matplotlib
is_ipython = 'inline' in matplotlib.get_backend()
if is_ipython:
    from IPython import display

plt.ion()

In [20]:
# Create a 2d tensor from an np array

a = np.random.rand(3,2)
a

array([[0.49871667, 0.60925154],
       [0.53656042, 0.68421532],
       [0.19659834, 0.96090497]])

In [21]:
# Convert to tensor

a_tensor = tf.convert_to_tensor(a)
a_tensor

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.49871667, 0.60925154],
       [0.53656042, 0.68421532],
       [0.19659834, 0.96090497]])>

In [22]:
a_tensor_dims = tf.expand_dims(a_tensor, 0)
a_tensor_dims

<tf.Tensor: shape=(1, 3, 2), dtype=float64, numpy=
array([[[0.49871667, 0.60925154],
        [0.53656042, 0.68421532],
        [0.19659834, 0.96090497]]])>

In [23]:
# tf reduce sum
# tf reduce max
# tf one hot
# masks

In [35]:
a_tensor[1].numpy()

array([0.53656042, 0.68421532])

In [25]:
tf.reduce_sum(a_tensor, 0)

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.23187543, 2.25437183])>

In [26]:
tf.reduce_sum(a_tensor, 1)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.1079682 , 1.22077574, 1.15750332])>

In [27]:
tf.reduce_max(a_tensor_dims, 0)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.49871667, 0.60925154],
       [0.53656042, 0.68421532],
       [0.19659834, 0.96090497]])>

In [28]:
tf.reduce_max(a_tensor_dims, 1)

<tf.Tensor: shape=(1, 2), dtype=float64, numpy=array([[0.53656042, 0.96090497]])>

In [29]:
tf.reduce_max(a_tensor_dims, 2)

<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[0.60925154, 0.68421532, 0.96090497]])>

In [33]:
masks = tf.one_hot(a_tensor[0].numpy(), 3)

In [31]:
indices = [0, 1, 2]
depth = 3
tf.one_hot(indices, depth)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [34]:
masks

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [1., 0., 0.]], dtype=float32)>