In [1]:
import numpy as np
import math
import random
import matplotlib
import matplotlib.pyplot as plt
from itertools import count

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# set up matplotlib
is_ipython = 'inline' in matplotlib.get_backend()
if is_ipython:
    from IPython import display

plt.ion()

In [34]:
# Create a 2d tensor from an np array

a = np.random.rand(3,2)
a

array([[0.30193671, 0.25952495],
       [0.95625024, 0.29932229],
       [0.4946474 , 0.50847456]])

In [35]:
# Convert to tensor

a_tensor = tf.convert_to_tensor(a)
a_tensor

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.30193671, 0.25952495],
       [0.95625024, 0.29932229],
       [0.4946474 , 0.50847456]])>

In [36]:
a_tensor_dims = tf.expand_dims(a_tensor, 0)
a_tensor_dims

<tf.Tensor: shape=(1, 3, 2), dtype=float64, numpy=
array([[[0.30193671, 0.25952495],
        [0.95625024, 0.29932229],
        [0.4946474 , 0.50847456]]])>

In [ ]:
tf reduce sum
tf reduce max
tf one hot
masks

In [45]:
a_tensor

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.30193671, 0.25952495],
       [0.95625024, 0.29932229],
       [0.4946474 , 0.50847456]])>

In [46]:
tf.reduce_sum(a_tensor, 0)

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.75283434, 1.0673218 ])>

In [47]:
tf.reduce_sum(a_tensor, 1)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.56146166, 1.25557253, 1.00312196])>

In [50]:
tf.reduce_max(a_tensor_dims, 0)

<tf.Tensor: shape=(1, 2), dtype=float64, numpy=array([[0.95625024, 0.50847456]])>

In [51]:
tf.reduce_max(a_tensor_dims, 1)

<tf.Tensor: shape=(1, 2), dtype=float64, numpy=array([[0.95625024, 0.50847456]])>

In [52]:
tf.reduce_max(a_tensor_dims, 2)

<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[0.30193671, 0.95625024, 0.50847456]])>

In [57]:
masks = tf.one_hot(a_tensor[0], 1)

InvalidArgumentError: Value for attr 'TI' of double is not in the list of allowed values: uint8, int8, int32, int64
	; NodeDef: {{node OneHot}}; Op<name=OneHot; signature=indices:TI, depth:int32, on_value:T, off_value:T -> output:T; attr=axis:int,default=-1; attr=T:type; attr=TI:type,default=DT_INT64,allowed=[DT_UINT8, DT_INT8, DT_INT32, DT_INT64]> [Op:OneHot]

In [56]:
indices = [0, 1, 2]
depth = 3
tf.one_hot(indices, depth)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>